### ISSUE TITLE
System.AggregateException: One or more errors occurred. 

### ISSUE THREAD

**Issue by diennttlu** [leizi-dev/QuartzRedisJobStoreCore#1]
System.AggregateException: 'One or more errors occurred. (Method 'ResetTriggerFromErrorState' in type 'QuartzRedisJobStoreCore.JobStore.RedisJobStore' from assembly 'QuartzRedisJobStoreCore.JobStore, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.)'

**Comment by leizi-dev** [comment]
Only applicable to. net6 projects

**Comment by diennttlu** [comment]
I got it done. Thanks!
